[mypy]

[mypy-python_graphql_client]
ignore_missing_imports = True

[mypy-bip_utils]
ignore_missing_imports = True
follow_untyped_imports = True

[mypy-coincurve]
ignore_missing_imports = True
follow_untyped_imports = True
