[tool.poetry]
name = "aptos-sdk"
version = "0.11.0"
description = "Aptos SDK"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/python/sdk"
keywords = ["web3", "sdk", "aptos", "blockchain"]

[tool.setuptools.package-data]
"aptos-sdk" = ["py.typed"]

[tool.poetry.dependencies]
ecdsa = "0.18.0"
python-graphql-client = "^0.4.3"
httpx = "^0.28.0"
PyNaCl = "^1.5.0"
python = ">=3.9.0"
tomli = "^2.2.0"
typing-extensions = "^4.4.0"
behave = "^1.2.6"
types-six = "^1.17.0"

[tool.poetry.dev-dependencies]
autoflake = "^2.3.0"
black = "^24.10.0"
coverage = "^7.6.0"
flake8 = "^7.1.0"
isort = "^5.13.0"
mypy = "^1.14.0"
mypy-extensions = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
