from _typeshed import Incomplete
from behave.model_core import Status as Status

class Reporter:
    config: Incomplete
    def __init__(self, config) -> None: ...
    def feature(self, feature) -> None: ...
    def end(self) -> None: ...
