name: "Python setup"
description: |
  Runs an opinionated and unified python setup action. It does the following:
  * Installs python
  * Installs uv
  * Installs a specified project, if given
inputs:
  pyproject_directory:
    description: "Optional path to a project with pyproject.toml"
    required: false

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Setup AikidoSec Safe Chain
      uses: aptos-labs/actions/akidosec-safe-chain@main

    - name: Install project
      if: inputs.pyproject_directory != ''
      run: uv sync --extra dev
      shell: bash
      working-directory: ${{ inputs.pyproject_directory }}
