from behave.formatter.base import Formatter as Formatter
from behave.formatter.base import StreamOpener as StreamOpener
from behave.importer import LazyDict as LazyDict
from behave.importer import LazyObject as LazyObject
from behave.importer import load_module as load_module
from behave.importer import parse_scoped_name as parse_scoped_name

def format_iter(): ...
def format_items(resolved: bool = False): ...
def register_as(name, formatter_class) -> None: ...
def register(formatter_class) -> None: ...
def register_formats(formats) -> None: ...
def load_formatter_class(scoped_class_name): ...
def select_formatter_class(formatter_name): ...
def is_formatter_valid(formatter_name): ...
def make_formatters(config, stream_openers): ...
