from _typeshed import Incomplete
from behave.formatter.base import Formatter as Formatter
from behave.model_core import Status as Status

class RerunFormatter(Formatter):
    name: str
    description: str
    show_timestamp: bool
    show_failed_scenarios_descriptions: bool
    failed_scenarios: Incomplete
    current_feature: Incomplete
    def __init__(self, stream_opener, config) -> None: ...
    def reset(self) -> None: ...
    def feature(self, feature) -> None: ...
    def eof(self) -> None: ...
    stream: Incomplete
    def close(self) -> None: ...
    def report_scenario_failures(self) -> None: ...
