from _typeshed import Incomplete

def iscoroutinefunction(func): ...
def is_context_manager(func): ...

class InvalidFixtureError(RuntimeError): ...

def use_fixture(fixture_func, context, *fixture_args, **fixture_kwargs): ...
def use_fixture_by_tag(tag, context, fixture_registry): ...
def fixture_call_params(fixture_func, *args, **kwargs): ...
def use_composite_fixture_with(context, fixture_funcs_with_params): ...
def fixture(
    func: Incomplete | None = None,
    name: Incomplete | None = None,
    pattern: Incomplete | None = None,
): ...
