from _typeshed import Incomplete
from behave.textutil import indent as indent

def escape_cell(cell): ...
def escape_triple_quotes(text): ...

class ModelDescriptor:
    @staticmethod
    def describe_table(table, indentation: Incomplete | None = None): ...
    @staticmethod
    def describe_docstring(doc_string, indentation: Incomplete | None = None): ...

class ModelPrinter(ModelDescriptor):
    stream: Incomplete
    def __init__(self, stream) -> None: ...
    def print_table(self, table, indentation: Incomplete | None = None) -> None: ...
    def print_docstring(self, text, indentation: Incomplete | None = None) -> None: ...
