from _typeshed import Incomplete

BEHAVE_UNICODE_ERRORS: Incomplete

def make_indentation(indent_size, part: str = " "): ...
def indent(text, prefix): ...
def compute_words_maxsize(words): ...
def is_ascii_encoding(encoding): ...
def select_best_encoding(outstream: Incomplete | None = None): ...
def text(
    value, encoding: Incomplete | None = None, errors: Incomplete | None = None
): ...
def to_texts(
    args, encoding: Incomplete | None = None, errors: Incomplete | None = None
): ...
def ensure_stream_with_encoder(stream, encoding: Incomplete | None = None): ...
