"""Example: Script payload construction (vs the common EntryFunction path).

Most transactions use EntryFunction to call published on-chain functions by name.
A Script transaction instead carries compiled Move bytecode directly — the code
runs once without being published. This is useful for:
- One-off operations that don't warrant deploying a module
- Complex atomic operations combining multiple module calls
- Scripts generated by tooling (e.g., governance proposals)

Key differences from EntryFunction:
- Script carries raw bytecode (bytes), not a module::function reference
- Arguments use ScriptArgument with explicit variant tags, not TransactionArgument
- TransactionPayload variant is SCRIPT (0), not ENTRY_FUNCTION (2)

ScriptArgument variants:
  ScriptArgument.U8         = 0
  ScriptArgument.U64        = 1
  ScriptArgument.U128       = 2
  ScriptArgument.ADDRESS    = 3
  ScriptArgument.U8_VECTOR  = 4
  ScriptArgument.BOOL       = 5
  ScriptArgument.U16        = 6
  ScriptArgument.U32        = 7
  ScriptArgument.U256       = 8
"""

import asyncio

from aptos_sdk_v2 import Account, Aptos, AptosConfig, Network
from aptos_sdk_v2.transactions import Script, ScriptArgument, TransactionPayload
from aptos_sdk_v2.types import StructTag, TypeTag

# ── About script bytecode ───────────────────────────────────────────────
#
# In a real workflow, you would compile a Move script with the Aptos CLI:
#
#   aptos move compile --named-addresses my_addr=0x1
#
# Then load the compiled bytecode:
#
#   script_code = Path("build/my_package/bytecode_scripts/my_script.mv").read_bytes()
#
# For this example, we use a minimal compiled script that transfers APT
# via 0x1::coin::transfer. The bytecode below was compiled from:
#
#   script {
#       use aptos_framework::coin;
#       use aptos_framework::aptos_coin::AptosCoin;
#
#       fun main(sender: &signer, recipient: address, amount: u64) {
#           coin::transfer<AptosCoin>(sender, recipient, amount);
#       }
#   }
#
# Note: compiled bytecode is version-specific. If this bytecode doesn't work
# on the current devnet, compile it yourself with the Aptos CLI.
TRANSFER_SCRIPT_BYTECODE = bytes.fromhex(
    "a11ceb0b060000000601000403040a050e0b07192c08452000000001"
    "00020001000003000100000103020301063c53454c463e0a617074"
    "6f735f636f696e094170746f73436f696e04636f696e087472616e"
    "73666572000000000000000000000000000000000000000000000000"
    "000000000001000001060b000b010b02380002"
)


async def main():
    config = AptosConfig(network=Network.DEVNET)
    async with Aptos(config) as aptos:
        # Create accounts
        alice = Account.generate()
        bob = Account.generate()
        print(f"Alice: {alice.address}")
        print(f"Bob:   {bob.address}")

        # Fund accounts
        print("\nFunding accounts...")
        await asyncio.gather(
            aptos.faucet.fund_account(alice.address, 100_000_000),
            aptos.faucet.fund_account(bob.address, 10_000_000),
        )

        # ── Build a Script payload ──────────────────────────────────────

        # Type arguments: the script above is generic over CoinType
        ty_args: list[TypeTag] = [
            TypeTag(StructTag.from_str("0x1::aptos_coin::AptosCoin")),
        ]

        # Script arguments use ScriptArgument with explicit variant tags.
        # The signer argument is implicit (not included here) — the VM
        # automatically passes the sender as &signer.
        args: list[ScriptArgument] = [
            ScriptArgument(ScriptArgument.ADDRESS, bob.address),
            ScriptArgument(ScriptArgument.U64, 7_000),
        ]

        script = Script(
            code=TRANSFER_SCRIPT_BYTECODE,
            ty_args=ty_args,
            args=args,
        )

        # Wrap in TransactionPayload — this selects variant SCRIPT (0)
        payload = TransactionPayload(script)

        # ── Build, sign, submit ─────────────────────────────────────────
        print("\nBuilding script transaction...")
        raw_txn = await aptos.transaction.build(
            sender=alice.address,
            payload=payload,
        )

        print("Signing and submitting...")
        result = await aptos.transaction.sign_submit_and_wait(raw_txn, alice)
        print(f"Transaction: {result['hash']}")
        print(f"Success: {result['success']}")
        print(f"VM status: {result['vm_status']}")

        # Verify the transfer
        bob_balance = await aptos.coin.balance(bob.address)
        print(f"\nBob balance: {bob_balance}")

        # ── Demonstration: building with different argument types ───────
        print("\n── ScriptArgument Types ──")
        print("The following ScriptArgument variants are available:")
        print(
            f"  U8         (variant {ScriptArgument.U8})   — ScriptArgument(ScriptArgument.U8, 255)"
        )
        print(
            f"  U16        (variant {ScriptArgument.U16})   — ScriptArgument(ScriptArgument.U16, 65535)"
        )
        print(
            f"  U32        (variant {ScriptArgument.U32})   — ScriptArgument(ScriptArgument.U32, 100)"
        )
        print(
            f"  U64        (variant {ScriptArgument.U64})   — ScriptArgument(ScriptArgument.U64, 1000)"
        )
        print(
            f"  U128       (variant {ScriptArgument.U128})   — ScriptArgument(ScriptArgument.U128, 1000)"
        )
        print(
            f"  U256       (variant {ScriptArgument.U256})   — ScriptArgument(ScriptArgument.U256, 1000)"
        )
        print(
            f"  ADDRESS    (variant {ScriptArgument.ADDRESS})   — ScriptArgument(ScriptArgument.ADDRESS, addr)"
        )
        print(
            f"  U8_VECTOR  (variant {ScriptArgument.U8_VECTOR})   — ScriptArgument(ScriptArgument.U8_VECTOR, b'\\x01\\x02')"
        )
        print(
            f"  BOOL       (variant {ScriptArgument.BOOL})   — ScriptArgument(ScriptArgument.BOOL, True)"
        )


if __name__ == "__main__":
    asyncio.run(main())
