name: "Devnet Examples"
permissions:
  contents: read
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-devnet-examples:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      APTOS_INDEXER_URL: https://api.devnet.aptoslabs.com/v1/graphql
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com/v1
      API_KEY: ${{ secrets.DEVNET_API_KEY }}
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_FAUCET_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - uses: ./.github/actions/python-setup
        with:
          pyproject_directory: .

      - name: Run examples on devnet
        run: make examples
        timeout-minutes: 20
