name: "Examples"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  push:
    branches:
      - main

jobs:
  run-python-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com/v1
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_FAUCET_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/python-setup
        with:
          pyproject_directory: .

      - uses: nick-fields/retry@v2
        name: py-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: make test && make examples
