name: "Localnet Examples"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  push:
    branches:
      - main

jobs:
  run-localnet-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_CORE_PATH: ./aptos-core
      APTOS_FAUCET_URL: http://127.0.0.1:8081
      APTOS_INDEXER_URL: http://127.0.0.1:8090/v1/graphql
      APTOS_NODE_URL: http://127.0.0.1:8080/v1
      APTOS_TEST_USE_EXISTING_NETWORK: true

    steps:
      - uses: actions/checkout@v4

      - name: Checkout aptos-core
        uses: actions/checkout@v4
        with:
          repository: aptos-labs/aptos-core
          path: './aptos-core'

      - name: Run a localnet
        uses: aptos-labs/actions/run-local-testnet@main
        with:
          node_version: v20.12.2
          pnpm_version: 8.15.6

      - uses: ./.github/actions/python-setup
        with:
          pyproject_directory: .

      - name: Install Aptos-CLI
        run: pnpm install -g @aptos-labs/aptos-cli
        shell: bash

      - name: Run examples on localnet
        run: make integration_test
        shell: bash
