name: "Testnet Examples"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  push:
    branches:
      - main

jobs:
  run-python-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_FAUCET_URL: https://faucet.testnet.aptoslabs.com
      APTOS_INDEXER_URL: https://api.testnet.aptoslabs.com/v1/graphql
      APTOS_NODE_URL: https://fullnode.testnet.aptoslabs.com/v1
      FAUCET_AUTH_TOKEN: ${{ secrets.TESTNET_FAUCET_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/python-setup
        with:
          pyproject_directory: .

      - name: Run examples on testnet
        uses: nick-fields/retry@v2
        with:
          max_attempts: 1
          timeout_minutes: 20
          command: make examples
